services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: collector
    restart: unless-stopped
    # networks:
    #   - mynet

  receiver:
    build:
      context: .
      dockerfile: Dockerfile.receiver
    container_name: receiver
    restart: unless-stopped
    env_file:
      - .env
    # networks:
    #   - mynet

  influxdb-monitor:
    image: influxdb:latest
    container_name: influxdb-monitor
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      #- DOCKER_INFLUXDB_INIT_RETENTION=30d
