services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.collector
    container_name: collector
    restart: unless-stopped
    # networks:
    #   - mynet

  forecast:
    build:
      context: .
      dockerfile: Dockerfile.forecast
    container_name: forecast
    # networks:
    #   - mynet

  receiver:
    build:
      context: .
      dockerfile: Dockerfile.receiver
    container_name: receiver
    restart: unless-stopped
    env_file:
      - .env
    # networks:
    #   - mynet

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    # volumes:
    #   - ./influxdb_data:/var/lib/influxdb2
    # networks:
    #   - mynet
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
      #- DOCKER_INFLUXDB_INIT_RETENTION=30d
